name: Deploy to AWS

on:
  push:
    branches:
      - main  # Altere para a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o SSH usando a versão correta da ação
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0  # Use a versão correta
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Passo 3: Executar comandos no servidor
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/ubuntu/meu-site
            echo "=== Iniciando Pull ==="
            git pull origin main
            echo "=== Ativando Ambiente Virtual ==="
            source venv/bin/activate
            echo "=== Instalando Dependências ==="
            pip install -r requirements.txt
            echo "=== Aplicando Migrações ==="
            python manage.py migrate
            echo "=== Coletando Arquivos Estáticos ==="
            python manage.py collectstatic --noinput
            echo "=== Reiniciando Serviços ==="
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo "=== Deploy Completo ==="
          EOF
